### ISSUE TITLE
Fix broken admin feature

### ISSUE THREAD

**Issue by ShaunOfTheLive** [ShaunOfTheLive/HangoutsBot#2]

**Comment by wardellbagby** [comment]
What do you mean by "broken admin feature?" What's wrong with it?

**Comment by ShaunOfTheLive** [comment]
Now that I've looked at it further, it's not actually _broken_. It's just that the test for user permissions defaults to letting _anybody_ run admin commands if you haven't specified "conversation_admin" and "commands_conversation_admin" for every conversation. I was assuming that by default, every conversation would just inherit the global admin settings, but actually you have to specify settings for each conversation that are a subset of the global settings, and if you don't, it just lets everybody have admin powers.

**Comment by wardellbagby** [comment]
Interesting. If you don't mind, I can go ahead and fix this upstream and you can update from that?

**Comment by ShaunOfTheLive** [comment]
Go ahead, thanks :+1:
